This notebook generates a .csv from Cear√°'s COVID-19 info (Conass)

1. Get data from Conass

In [37]:
import pandas as pd
from tableauscraper import TableauScraper as TS

url = "https://public.tableau.com/shared/6KJMF6FW2?:display_count=y&:origin=viz_share_link&:embed=y"

ts = TS()
ts.loads(url)
dashboard = ts.getDashboard()

2. Data cleaning and visualization

In [87]:
# value or alias
column_type = "value"
df_cases = dashboard.worksheets[2].data.filter(like = column_type, axis = 1)
df_deaths = dashboard.worksheets[4].data.filter(like = column_type, axis = 1)
df = pd.merge(df_cases, df_deaths, on=f"nu_semana_epi-{column_type}", suffixes=('', '_y'))
# Removes duplicated columns
to_drop = [x for x in df if x.endswith('_y')]
df = df.drop(to_drop, axis=1)
# Renames columns for better human comprehension
df = df.rename(columns={
    "MIN(dt_coleta)-value": "data_inicio", 
    "nu_semana_epi-value": "semana_epidemiologica", 
    "SUM(qt_caso_novo)-value": "novos_casos",
    "SUM(qt_obito_nono)-value": "obitos"
})
# Reorders columns
cols = list(df.columns)
a, b = cols.index('data_inicio'), cols.index('semana_epidemiologica')
cols[b], cols[a] = cols[a], cols[b]
df = df[cols]
# Displays dataframe
display(df)

   semana_epidemiologica data_inicio novos_casos obitos
0                     13  2020-03-27         322      4
1                     14  2020-03-29         408     18
2                     15  2020-04-05         918     52
3                     16  2020-04-12        1380    106
4                     17  2020-04-19        2614    145
5                     19  2020-05-03        7485    426
6                     20  2020-05-10        7619    552
7                     21  2020-05-17       10577    694
8                     22  2020-05-24       12566    648
9                     23  2020-05-31       15354   1009
10                    24  2020-06-07       12807    864
11                    25  2020-06-14       15688    689
12                    26  2020-06-21       14498    463
13                    27  2020-06-28       14308    430
14                    28  2020-07-05       15006    442
15                    29  2020-07-12       10601    320
16                    30  2020-07-19       15042    303
17                    31  2020-07-26       14201    222
18                    32  2020-08-02       12424    253
19                    33  2020-08-09        9089    178
20                    34  2020-08-16        7017    157
21                    35  2020-08-23        9644     96
22                    36  2020-08-30        8026    183
23                    37  2020-09-06        4802    120
24                    38  2020-09-13        6511    116
25                    39  2020-09-20        4930    112
26                    40  2020-09-27        4020    137
27                    41  2020-10-04       15943     80
28                    42  2020-10-11        4569     77
29                    43  2020-10-18        5039     39
30                    44  2020-10-25        4765    107
31                    45  2020-11-01        3718     38
32                    46  2020-11-08        6137     48
33                    47  2020-11-15        6325     48
34                    48  2020-11-22        8305    111
35                    49  2020-11-29        4993     95
36                    50  2020-12-06        9731     81
37                    51  2020-12-13        7407    135
38                    52  2020-12-20        4838     43
39                    53  2020-12-27        8364     63
40                     1  2021-01-03        6956    122
41                     2  2021-01-10        8238     86
42                     3  2021-01-17        8327     97
43                     4  2021-01-24        9265    145
44                     5  2021-01-31       10926    142
45                     6  2021-02-07        9330    134
46                     7  2021-02-14       16797    197

Finally, generates and saves the

In [89]:
# index = false means the dataframe's row indexes won't be saved as the first column of .csv file
df.to_csv('notchbooks/conass-covid-extractor/ceara-covid19-conass-info.csv', index=False)